modLoader="javafml" 
loaderVersion="[28,)" 
#issueTrackerURL=""

[[mods]] 
modId="create"
version="${file.jarVersion}"
displayName="Create" 
#updateJSONURL=""
authors="simibubi" 
description='''
Technology that empowers the player.'''

[[dependencies.create]] 
    modId="forge"
    mandatory=true 
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"